sudo: true

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS hxphp;'

language: php

dist: trusty

php:
  - 7.1
  - 7.2

script: 
  - composer install
  - phpunit

notifications:
  email:
    - bruno@plug.ag